### ISSUE TITLE
Retrieve EK

### ISSUE THREAD

**Issue by tabajara-scontain** [parallaxsecond/rust-tss-esapi#383] opened 2022-12-13 16:37 UTC
Hi all,

I'm having trouble retrieving the EK from a simulated TPM (SWTPM).
Every time I try to read the certificate I get and error: `WrapperError(InvalidHandleState)`

It seems function `tr_from_tpm_public` is being called twice, and `Esys_TR_FromTPMPublic` fetches the same nv index.
 
 The snippet I'm trying to execute is the one below. I also tried to run your [tests](https://github.com/parallaxsecond/rust-tss-esapi/blob/072bd208548f39ef428270527039de67cadede96/tss-esapi/tests/integration_tests/abstraction_tests/ek_tests.rs) to retrieve the EK changing the simulator from MSSIM to SWTPM, and it also fails. 
 
 ```rust
 let mut context = Context::new(TctiNameConf::from_str("swtpm:port=2321,host=localhost")?)?;
 
 let ek_certificate = &ek::retrieve_ek_pubcert(&mut context, AsymmetricAlgorithm::Rsa)?;
 ```
 
 Any ideas on what the problem can be?
 
 Setup:
 - tss-esapi: 7.1.0 
 - swtpm: 0.8.0
 - tpm2-tss: 3.2.1

**Comment by ionut-arm** [comment] 2022-12-13 17:20
Hey! Before I dive into it too much, could you try using the tip of `main` for `tss-esapi`, instead of `7.1.0`? We've had some changes in that area since the release, it might solve the problem. We'll worry about what that means release-wise afterwards.

**Comment by tabajara-scontain** [comment] 2022-12-14 06:36
Hi, I downloaded the source code from the main and executed the test below using SWTPM instead of MSSIM.

```
running 1 test
[2022-12-14T06:26:31Z ERROR tss_esapi::context::handle_manager] Handle(1078035592) is already open
test abstraction_tests::ek_tests::test_retrieve_ek_pubcert ... FAILED
```

**Sidenote**: when building rust-tss-esapi I got `Unsupported TSS version 3.2.1-rc0`. I just ignored it. Let me know if I shouldn't have.

**Comment by ionut-arm** [comment] 2022-12-14 15:46
Hmmm, ok, will try to reproduce - a bit weird, we already have CI jobs using `swtpm` and running that particular test.

**Comment by ansasaki** [comment] 2023-01-23 14:04
This looks related: https://github.com/tpm2-software/tpm2-tss/issues/2537

**Comment by ansasaki** [comment] 2023-01-26 11:50
I'm also having problems to get the EK certificate when using `tpm2-tss 3.2.1`. When I downgrade it to `tpm2-tss 3.2.0` the same code works fine.

On my debug log I get:
```
ERROR tss_esapi::context::handle_manager > Handle(1078035594) is already open
```
And the error received is an `InvalidHandleState`.

Apparently , for `tpm2-tools` a workaround was applied: https://github.com/tpm2-software/tpm2-tools/pull/2847. There is an open issue to track this: https://github.com/tpm2-software/tpm2-tools/issues/3156

Hopefully this goes away with https://github.com/parallaxsecond/rust-tss-esapi/issues/382

**Comment by ansasaki** [comment] 2023-01-31 10:27
@ionut-arm FYI, for tpm2-tss developers, this is a bug in rust-tss-esapi side:

https://github.com/tpm2-software/tpm2-tss/issues/2537#issuecomment-1406539188

**Comment by ionut-arm** [comment] 2023-01-31 11:19
Thanks, that's good to know, thank you for helping trace it!

**Comment by Superhepper** [comment] 2023-01-31 11:21
Should be an easy fix.

**Comment by ionut-arm** [comment] 2023-02-06 23:50
Hi all, this should now be fixed in `tss-esapi` 7.2.0. Please let me know if that's not the case

**Comment by wiktor-k** [comment] 2023-02-16 07:42
@ionut-arm maybe it's OK to close this ticket? If the issue persists we can still re-open...

**Comment by TabajaraKrausburg** [comment] 2023-02-16 07:53
Hi guys, thank you very much for tackling this issue! I haven't had the chance to test it yet, though. I plan to do it soon. So, please don't hesitate to close it. Once again, thanks!

**Closed** 2023-04-17 18:24 UTC
